FROM pypy:3

# Update packages and install setup requirements.
RUN apt-get update && \
	apt-get install -y  build-essential libpq-dev

# Set WORKDIR to /src
WORKDIR /src

# Add and install Python modules
ADD requirements.txt /src/requirements.txt
RUN pip install -r requirements.txt

# Bundle app source
ADD . /src

# Install main module
RUN pypy3 setup.py install

# Expose web port
EXPOSE 5000
