version: '2'
services:
  parser:
    image: generalprogramming/tumblr-api-pipeline
    build: .
    restart: always
    command: "python3 apipipeline/server_parser.py"
    env_file: .env

  queue_loader:
    image: generalprogramming/tumblr-api-pipeline
    build: .
    restart: always
    command: "python3 apipipeline/server_load_queue.py"
    env_file: .env